[package]
name = "rust_feed_updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "0.3.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
